// The Duet question deck — 200 questions across six categories, picked deterministically per
// couple per day (hash of coupleId + date). Voice rules: askable out loud over dinner, no
// therapy-speak, no quiz-show cuteness; conflict-repair questions assume goodwill; intimacy
// questions are warm, never explicit. A couple takes ~7 months to see a repeat.

export type CoupleQuestion = { id: string; category: string; text: string };

const q = (category: string, i: number, text: string): CoupleQuestion => ({
  id: `${category}-${i}`,
  category,
  text,
});

const playful = [
  "If we swapped jobs for a day, what part of mine would break you first?",
  "What's a tiny habit of mine you secretly find funny?",
  "Which fictional couple are we closest to on a bad day?",
  "What would our band be called, and who's clearly the diva?",
  "What's the most ridiculous thing we've ever argued about?",
  "If we opened a shop together, what would it sell?",
  "What song would play when I walk into a room, in your version of the movie?",
  "What's my most predictable move that you can see coming a mile off?",
  "If you had to describe me using only three objects in our home, which three?",
  "What's a talent I think I have that you have doubts about?",
  "Which of us would survive longer in a horror film, and why?",
  "What nickname have you almost called me that you never said out loud?",
  "If our pets (real or future) could talk, what would they say about us?",
  "What's the funniest misunderstanding we've ever had?",
  "Which meal that I make (or order) says the most about me?",
  "If we were a two-person heist crew, who plans and who improvises?",
  "What's something I do in my sleep or half-asleep that amuses you?",
  "What tiny hill would I absolutely die on?",
  "If you could add one completely unnecessary rule to our home, what would it be?",
  "What's the most tourist-y thing you'd secretly love to do together?",
  "Which emoji is basically me?",
  "What would I be famous for in a small, very specific way?",
  "If we had a family crest, what three things go on it?",
  "What's a word or phrase I say way too often?",
  "Which of us is more likely to become eccentric with age, and how?",
  "What's the best bad decision we've made together?",
  "If you could watch me from the outside for one day, which day would you pick?",
  "What's my superpower in social situations — and my kryptonite?",
  "If our relationship had a mascot, what would it be?",
  "What's something I'm weirdly precise about?",
  "Which of my clothes would you quietly retire, given the chance?",
  "What game or sport would we be unbeatable at as a pair?",
  "What's the strangest compliment you've ever wanted to give me?",
].map((t, i) => q("playful", i + 1, t));

const deep = [
  "What's something you believed about love before us that you don't believe anymore?",
  "When did you last feel truly seen by me?",
  "What part of your inner life do you find hardest to put into words?",
  "What's a fear you carry that you rarely say out loud?",
  "Which version of yourself are you most afraid I'll meet one day?",
  "What did your childhood teach you about how love is supposed to work?",
  "What's something you need that you find embarrassing to need?",
  "When do you feel loneliest — even with me around?",
  "What's a belief of yours that has quietly changed since we met?",
  "What would you want me to understand about you without having to explain it?",
  "What's the hardest thing you've ever told me — and how did it land?",
  "Where in your life are you performing rather than living?",
  "What are you still hoping I'll notice about you?",
  "What does 'home' actually mean to you — place, person, or feeling?",
  "What's a grief you're still carrying that predates us?",
  "When have you felt proudest of who you are?",
  "What's the difference between who you are with me and who you are alone?",
  "What question do you wish I asked you more often?",
  "What's something you've forgiven me for that I never knew needed forgiving?",
  "Which of your parents' patterns do you catch yourself repeating?",
  "What does your ambition cost you — and us?",
  "When did you last change your mind about something important, and what did it?",
  "What's a truth about yourself you accepted late?",
  "What do you do with feelings you don't want me to see?",
  "What's the kindest thing anyone has ever done for you?",
  "Where does your confidence actually come from — and when does it desert you?",
  "What are you most afraid of wasting?",
  "If you could re-live one ordinary day from before we met, which one?",
  "What's something you want to be true about you that isn't yet?",
  "What part of getting older secretly appeals to you?",
  "What would you want said about you when you're not in the room?",
  "What's the bravest thing you've done that nobody clapped for?",
  "What do you believe about us that you've never said plainly?",
].map((t, i) => q("deep", i + 1, t));

const gratitude = [
  "What's something I did this week that made your life quietly easier?",
  "What's a small ritual of ours you'd genuinely miss?",
  "When did I last make you laugh at a moment you needed it?",
  "What's something about my family or friends you're grateful for?",
  "Which of my flaws have you come to almost like?",
  "What's a way I've changed you for the better without trying to?",
  "What do I do in hard moments that helps more than I know?",
  "What's the most ordinary thing about our life that you'd defend fiercely?",
  "When were you most relieved I was the person next to you?",
  "What's something I taught you — practically or otherwise?",
  "What part of my routine do you find oddly comforting?",
  "What did you underestimate about me at the start?",
  "What's a sacrifice I made that you still think about?",
  "When did I surprise you most, in a good way?",
  "What's your favorite thing I do without noticing I do it?",
  "Which meal, trip, or evening together would you relive exactly as it was?",
  "What's something my hands do that you love — cooking, fixing, holding?",
  "When have you felt proudest to introduce me?",
  "What worry did I once talk you out of that stayed talked-out?",
  "What's a way I show love that isn't words?",
  "What's the best advice I've given you — even if you ignored it at first?",
  "What about the way I treat strangers matters to you?",
  "When did you last look at me and feel lucky, and what was I doing?",
  "What's something you stopped worrying about because I exist?",
  "Which of my small kindnesses do you suspect I don't remember?",
  "What's the most useful thing I nag you about?",
  "What's a difficult season we passed through that you're grateful we faced together?",
  "What do you love that I made — a thing, a plan, a habit, a home?",
  "When does my voice, specifically, help?",
  "What's something about my body you're grateful for — strength, warmth, the way I'm here?",
  "What tradition of ours do you hope we never lose?",
  "What did I get right this month that I probably didn't notice?",
  "Who would you be right now if we'd never met — and what do you like better about this version?",
].map((t, i) => q("gratitude", i + 1, t));

const repair = [
  "What's something small I do that lands harder than I probably intend?",
  "When we argue, what do you actually need first — space, warmth, or solutions?",
  "What's a recurring argument of ours that's really about something else?",
  "What do you wish I understood about how you go quiet?",
  "What's the hardest thing about apologizing to me?",
  "When did I last hurt you slightly and never notice?",
  "What's something you've been holding that would be lighter said out loud?",
  "How do you know when I'm really listening — and when I'm just waiting to talk?",
  "What does my anger look like from your side of it?",
  "What's one thing we could change about how we disagree?",
  "What do you need me to stop explaining and just hear?",
  "Which of your buttons do I press without meaning to?",
  "What's an old wound between us that healed crooked?",
  "When you say 'I'm fine', what should I actually do?",
  "What's the most useful thing I've ever done after a fight?",
  "What conversation are we both avoiding?",
  "How can I make it safer for you to tell me hard things?",
  "What's something you criticized in me that you now see differently?",
  "When we're both tired and short, what's our best exit ramp?",
  "What did your family do with conflict that we've inherited?",
  "What's a boundary you've wanted to ask for but haven't?",
  "What does being forgiven feel like to you — and have I given you that feeling?",
  "Which of my jokes sometimes isn't funny from where you sit?",
  "What's the first sign, in you, that resentment is building?",
  "What would help you come back to me faster after we clash?",
  "What's something I dismissed that mattered more than I realized?",
  "Where do you feel unheard in the day-to-day logistics of our life?",
  "What promise between us needs renewing?",
  "If we could replay one argument with cooler heads, which one?",
  "What do you need on the days you don't like yourself much?",
  "What's the gentlest true thing you could tell me right now that's still hard?",
  "How should I bring something up when I know it'll sting?",
  "What repair have we gotten genuinely good at?",
].map((t, i) => q("repair", i + 1, t));

const future = [
  "What's something you hope we're still doing at eighty?",
  "If money stopped mattering tomorrow, what would our Tuesdays look like?",
  "What skill do you want us to learn together?",
  "Where do you secretly want to live for a year?",
  "What kind of old couple do you refuse to become?",
  "What's a trip you've imagined for us but never proposed?",
  "What do you want our home to feel like to people who visit?",
  "What tradition should we invent this year?",
  "What's a fear you have about our future that saying might shrink?",
  "What role do you hope we play in our friends' lives as we age?",
  "What would you want us to be known for as a pair?",
  "What's one thing our future selves will wish we'd started now?",
  "How do you want us to handle money when it's tight — and when it isn't?",
  "What part of your career dream still needs my backing?",
  "What would a perfect ordinary Saturday look like in ten years?",
  "What do you want more of in our life by this time next year?",
  "If we wrote a letter to ourselves to open in five years, what must it mention?",
  "What's something you want to build, grow, or make with me — literally?",
  "How should we celebrate the next thing that deserves celebrating?",
  "What worries you about how the world is changing, for us specifically?",
  "What's a promise about the future you'd like from me — realistic ones only?",
  "Which older couple do we quietly want to become, and what do they have?",
  "What does retirement actually mean to you — rest, reinvention, or escape?",
  "What would you want us to do differently from our parents' marriages?",
  "What adventure keeps getting postponed that shouldn't survive another year?",
  "What's the next hard conversation our future needs us to have?",
  "If we could guarantee one thing about our life in twenty years, what would you pick?",
  "What do you hope never changes about how we talk to each other?",
  "What season of life are you most looking forward to sharing?",
  "What would you want to be true about our last decade together?",
  "What's a small upgrade to our daily life we keep not making?",
  "Who do you hope we're brave enough to stay close to — or walk away from?",
  "What's the first thing we should do when the next stretch of luck hits?",
].map((t, i) => q("future", i + 1, t));

const intimacy = [
  "When do you feel closest to me — the actual moment, not the category?",
  "What's a way you like being touched that you've never quite asked for?",
  "What did you find attractive about me this week — be specific?",
  "When did you last miss me while I was in the same room?",
  "What's the difference between feeling wanted and feeling needed, for you?",
  "What makes you feel desired at this age, in this body, in this life?",
  "What's a moment of ours you replay when you're away from me?",
  "What does affection look like on the days words are too much?",
  "What are you shy about with me, even now?",
  "What's the most intimate non-physical thing we do?",
  "How has wanting each other changed since the beginning — honestly?",
  "What do you need to feel safe enough to be fully yourself with me?",
  "What's something about my presence — smell, warmth, sound — that steadies you?",
  "When do you feel most beautiful or handsome, and am I part of it?",
  "What would make our evenings feel closer, starting this week?",
  "What's a kind of date we've never tried that you'd actually love?",
  "What compliment about you, from me, would land deepest right now?",
  "How do you like to be comforted when the day has been unkind?",
  "What's the story of one of your favorite kisses of ours?",
  "What part of being known by me is still slightly terrifying?",
  "What ritual of closeness should we protect from busyness?",
  "When have you felt most proud of our physical life together?",
  "What does 'romance' actually mean to you — strip away the movies?",
  "What's a slow thing you wish we did more, in a fast life?",
  "How do you want to be looked at?",
  "What's something tender you've thought about me this month and not said?",
  "Where in your body do you carry stress, and how could my hands help?",
  "What's your favorite ordinary intimacy — the coffee handoff, the hallway pass?",
  "What would you want the first ten minutes after a long separation to look like?",
  "What's a memory of us that still makes you blush?",
  "What does falling asleep next to me do for you?",
  "How should I love you on the days you can't say what you need?",
  "What's one thing about our closeness you'd never trade for excitement?",
].map((t, i) => q("intimacy", i + 1, t));

export const COUPLE_DECK: CoupleQuestion[] = [
  ...playful,
  ...deep,
  ...gratitude,
  ...repair,
  ...future,
  ...intimacy,
];

const BY_ID = new Map(COUPLE_DECK.map((c) => [c.id, c]));
export const coupleQuestionById = (id: string): CoupleQuestion | null => BY_ID.get(id) ?? null;

/** Deterministic per-couple daily pick: same question for both partners all day, different per couple. */
export function coupleQuestionFor(coupleId: string, dateKey: string): CoupleQuestion {
  const s = `${coupleId}:${dateKey}`;
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return COUPLE_DECK[Math.abs(h) % COUPLE_DECK.length];
}
