// The seeded daily-prompt library (journiv's deterministic model): 150 prompts, picked by a hash
// of the date so every day gets one stable prompt and the library takes five months to repeat.
// Voice rules: plain words, one question, no "journaling about journaling", no toxic positivity —
// an invitation, never an assignment. The personalized theme-prompt (from the user's own signals)
// still outranks these; this library is the floor, and the floor should be good.

export const PROMPT_LIBRARY: string[] = [
  // today, plainly
  "What's true today, even if it's small?",
  "What's taking up the most room in your mind right now?",
  "What are you looking forward to — or dreading?",
  "If today had a title, what would it be?",
  "What did today ask of you?",
  "What would you tell a friend who'd had your day?",
  "What's one thing you noticed today that nobody else did?",
  "Where did today actually go?",
  "What deserved more attention today than it got?",
  "What was the best ninety seconds of today?",
  // feelings, named
  "What feeling has been in the background all day?",
  "What are you pretending not to feel?",
  "When did you last feel completely at ease? What was around you?",
  "What's the difference between how today looked and how it felt?",
  "What made you laugh recently — really laugh?",
  "What's been sitting heavy that you haven't said out loud?",
  "Which feeling do you trust least in yourself, and why?",
  "What would relief look like right now?",
  "What are you angrier about than you're letting on?",
  "What softened you this week?",
  // people
  "Who did you think about today that you didn't talk to?",
  "What's a conversation you're rehearsing but not having?",
  "Who gets the best version of you? Who gets the leftovers?",
  "What did someone do recently that you haven't thanked them for?",
  "Who are you slowly drifting from — and is it drift or choice?",
  "What do the people closest to you not know about this week?",
  "Whose approval are you still working for?",
  "Who could you call right now, and what stops you?",
  "What's something a stranger did that stayed with you?",
  "Who taught you something this year without meaning to?",
  // work and effort
  "What part of your work still feels like yours?",
  "What are you building that no one is asking you to build?",
  "Where are you working hard on the wrong thing?",
  "What would you stop doing tomorrow if nobody minded?",
  "What did you do this week that you'd defend to anyone?",
  "When did work last surprise you?",
  "What's the task you keep re-adding to the list? What's it really asking?",
  "If effort were visible, where would yours be piled up?",
  "What compliment about your work do you have trouble believing?",
  "What's worth doing badly at first?",
  // the body
  "What has your body been telling you lately that you've overruled?",
  "Where does stress live in you? What loosens it?",
  "When did you last move in a way that felt good, not dutiful?",
  "What did sleep — or the lack of it — do to this week?",
  "What does your energy actually follow: people, light, food, purpose?",
  "What would resting properly look like, concretely, this week?",
  "What's one thing your body did today that deserves credit?",
  "What are you eating for that isn't hunger?",
  "When do you feel strongest?",
  "What's your breath been like today — and what does that tell you?",
  // memory
  "What memory came back recently, uninvited? Why now?",
  "What's something you did years ago that still shapes today?",
  "Which version of you would be most surprised by your life now?",
  "What's a smell or song that opens a door? Walk through it.",
  "What did you believe five years ago that you've quietly stopped believing?",
  "What's a day you'd relive exactly as it was?",
  "What have you forgiven that you never announced?",
  "What's an ordinary moment from childhood that turned out to matter?",
  "Who were you at nineteen? Be fair.",
  "What's the story you tell about yourself that might need re-telling?",
  // fear and risk
  "What are you afraid would happen if you stopped managing everything?",
  "What's the risk you keep circling without taking?",
  "What's the worst that could happen — actually written out, not felt?",
  "When did you last do something before you felt ready?",
  "What fear has quietly expired without you noticing?",
  "What would you attempt if failure stayed private?",
  "Where are you brave that you don't give yourself credit for?",
  "What's the difference between your caution and your fear?",
  "What scares you about getting what you want?",
  "What did you survive that you were sure you wouldn't?",
  // values
  "What did you defend this week — and what did you let slide?",
  "When were you last proud of how you behaved, not what you achieved?",
  "What matters to you that costs you something to keep mattering?",
  "Where is your time going against your own stated priorities?",
  "What compromise is starting to feel less temporary?",
  "What do you want to be reliable for?",
  "What line wouldn't you cross, even for a good outcome?",
  "What are you loyal to out of habit rather than belief?",
  "When did you last change your mind about something important?",
  "What does 'enough' look like for you, in numbers or in mornings?",
  // change
  "What's ending right now, slowly enough that it's easy to miss?",
  "What's beginning that you haven't named yet?",
  "What are you holding onto mostly because you've held it so long?",
  "What would this season of your life be called?",
  "What's different about you since this time last year?",
  "What change did you resist that turned out fine — or better?",
  "What are you waiting for permission to do?",
  "If nothing changes, where does this road actually go?",
  "What's one small thing you could stop carrying this week?",
  "What part of your routine no longer fits the person running it?",
  // wanting
  "What do you want that you haven't admitted wanting?",
  "What did you want badly once and then stop wanting? What happened?",
  "Whose life makes you envious — and what's the envy pointing at?",
  "What would a good year from now look like, specifically?",
  "What do you keep buying instead of the thing you actually want?",
  "If someone gave you three free hours tomorrow, what would you honestly do?",
  "What's the smallest version of the dream that would still count?",
  "What are you hungry for that food doesn't fix?",
  "What would you do with certainty, if certainty were available?",
  "What does your ambition cost the rest of you?",
  // gratitude, without the greeting card
  "What went right today that had every chance to go wrong?",
  "Who made your life easier this week without being asked?",
  "What do you rely on that you never think about?",
  "What's beautiful within ten meters of you right now?",
  "What did past-you set up that present-you gets to enjoy?",
  "What's something hard from before that you're now glad happened?",
  "What ability do you use daily that you once didn't have?",
  "What made today easier than yesterday?",
  "Which small comfort would you miss most?",
  "What's working? Start there.",
  // play and aliveness
  "When did you last lose track of time? Doing what?",
  "What did you love doing before it had to be useful?",
  "What would you do today if it only had to be fun?",
  "What's something silly you take seriously — keep going.",
  "Where does your curiosity keep wandering when you let it?",
  "What did you make recently — anything, of any size?",
  "What would you try if nobody would ever see the result?",
  "What music fits today? Why that?",
  "When do you feel most like yourself?",
  "What's an experiment worth running this month?",
  // the hard stuff
  "What are you tired of being strong about?",
  "What conversation went wrong that you keep replaying?",
  "What loss are you still in the middle of, whatever the calendar says?",
  "What apology are you owed that you'll probably never get?",
  "What are you doing to yourself that you'd never accept for a friend?",
  "Where does it still hurt when you press on it?",
  "What do you need that feels embarrassing to need?",
  "What's the loneliest part of your week?",
  "What truth are you handling by staying busy?",
  "What would you say if you knew it would be received kindly?",
  // perspective
  "What will matter about this month in ten years? What won't?",
  "What advice do you give others that you're not taking?",
  "What would your eighty-year-old self notice about today?",
  "What problem of yours would someone else love to have?",
  "What are you certain about that deserves a second look?",
  "If this year were a chapter, what would the chapter be doing for the book?",
  "What's obvious to you now that took years to learn?",
  "What are you measuring your days by — and is it the right ruler?",
  "Which of today's worries will you not remember in June?",
  "What does the evidence of your life say you actually value?",
  // the future, gently
  "What's the next right thing — not the whole plan, just the next thing?",
  "What are you building toward that you could name in one sentence?",
  "What would you like to be true by winter?",
  "What appointment with yourself do you keep cancelling?",
  "What's the kindest realistic thing next week could hold?",
  "What skill would change things if you gave it a season?",
  "What are you putting off until you feel 'ready' — and what's ready even mean?",
  "Who do you want to have been, once this stretch is over?",
  "What seed could you plant today that costs almost nothing?",
  "What would future-you thank you for doing this week?",
];

/** FNV-1a of the date key → a stable index into the library. Different every day, cycles in ~5 months. */
export function promptForDate(dateKey: string): string {
  let h = 2166136261;
  for (let i = 0; i < dateKey.length; i++) {
    h ^= dateKey.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return PROMPT_LIBRARY[Math.abs(h) % PROMPT_LIBRARY.length];
}
