/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearRouteImport } from './routes/year'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TheIndexRouteImport } from './routes/the-index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RememberedRouteImport } from './routes/remembered'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnThisDayRouteImport } from './routes/on-this-day'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FutureRouteImport } from './routes/future'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const YearRoute = YearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TheIndexRoute = TheIndexRouteImport.update({
  id: '/the-index',
  path: '/the-index',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RememberedRoute = RememberedRouteImport.update({
  id: '/remembered',
  path: '/remembered',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnThisDayRoute = OnThisDayRouteImport.update({
  id: '/on-this-day',
  path: '/on-this-day',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/insights': typeof InsightsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/remembered': typeof RememberedRoute
  '/settings': typeof SettingsRoute
  '/the-index': typeof TheIndexRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/insights': typeof InsightsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/remembered': typeof RememberedRoute
  '/settings': typeof SettingsRoute
  '/the-index': typeof TheIndexRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/insights': typeof InsightsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/remembered': typeof RememberedRoute
  '/settings': typeof SettingsRoute
  '/the-index': typeof TheIndexRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/chat'
    | '/extension'
    | '/future'
    | '/insights'
    | '/on-this-day'
    | '/onboarding'
    | '/remembered'
    | '/settings'
    | '/the-index'
    | '/today'
    | '/upgrade'
    | '/wrapped'
    | '/year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/chat'
    | '/extension'
    | '/future'
    | '/insights'
    | '/on-this-day'
    | '/onboarding'
    | '/remembered'
    | '/settings'
    | '/the-index'
    | '/today'
    | '/upgrade'
    | '/wrapped'
    | '/year'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/chat'
    | '/extension'
    | '/future'
    | '/insights'
    | '/on-this-day'
    | '/onboarding'
    | '/remembered'
    | '/settings'
    | '/the-index'
    | '/today'
    | '/upgrade'
    | '/wrapped'
    | '/year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ChatRoute: typeof ChatRoute
  ExtensionRoute: typeof ExtensionRoute
  FutureRoute: typeof FutureRoute
  InsightsRoute: typeof InsightsRoute
  OnThisDayRoute: typeof OnThisDayRoute
  OnboardingRoute: typeof OnboardingRoute
  RememberedRoute: typeof RememberedRoute
  SettingsRoute: typeof SettingsRoute
  TheIndexRoute: typeof TheIndexRoute
  TodayRoute: typeof TodayRoute
  UpgradeRoute: typeof UpgradeRoute
  WrappedRoute: typeof WrappedRoute
  YearRoute: typeof YearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year': {
      id: '/year'
      path: '/year'
      fullPath: '/year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-index': {
      id: '/the-index'
      path: '/the-index'
      fullPath: '/the-index'
      preLoaderRoute: typeof TheIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remembered': {
      id: '/remembered'
      path: '/remembered'
      fullPath: '/remembered'
      preLoaderRoute: typeof RememberedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-this-day': {
      id: '/on-this-day'
      path: '/on-this-day'
      fullPath: '/on-this-day'
      preLoaderRoute: typeof OnThisDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ChatRoute: ChatRoute,
  ExtensionRoute: ExtensionRoute,
  FutureRoute: FutureRoute,
  InsightsRoute: InsightsRoute,
  OnThisDayRoute: OnThisDayRoute,
  OnboardingRoute: OnboardingRoute,
  RememberedRoute: RememberedRoute,
  SettingsRoute: SettingsRoute,
  TheIndexRoute: TheIndexRoute,
  TodayRoute: TodayRoute,
  UpgradeRoute: UpgradeRoute,
  WrappedRoute: WrappedRoute,
  YearRoute: YearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
