/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearRouteImport } from './routes/year'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as WellbeingRouteImport } from './routes/wellbeing'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as TheIndexRouteImport } from './routes/the-index'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RememberedRouteImport } from './routes/remembered'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnThisDayRouteImport } from './routes/on-this-day'
import { Route as IntentionsRouteImport } from './routes/intentions'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FutureRouteImport } from './routes/future'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DuetRouteImport } from './routes/duet'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CommitRouteImport } from './routes/commit'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CardRouteImport } from './routes/card'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ArchetypeRouteImport } from './routes/archetype'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'

const YearRoute = YearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const WellbeingRoute = WellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const TheIndexRoute = TheIndexRouteImport.update({
  id: '/the-index',
  path: '/the-index',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RememberedRoute = RememberedRouteImport.update({
  id: '/remembered',
  path: '/remembered',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnThisDayRoute = OnThisDayRouteImport.update({
  id: '/on-this-day',
  path: '/on-this-day',
  getParentRoute: () => rootRouteImport,
} as any)
const IntentionsRoute = IntentionsRouteImport.update({
  id: '/intentions',
  path: '/intentions',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DuetRoute = DuetRouteImport.update({
  id: '/duet',
  path: '/duet',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitRoute = CommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypeRoute = ArchetypeRouteImport.update({
  id: '/archetype',
  path: '/archetype',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetype': typeof ArchetypeRoute
  '/ask': typeof AskRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/canvas': typeof CanvasRoute
  '/card': typeof CardRoute
  '/chat': typeof ChatRoute
  '/commit': typeof CommitRoute
  '/create': typeof CreateRoute
  '/duet': typeof DuetRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/history': typeof HistoryRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/intentions': typeof IntentionsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/programs': typeof ProgramsRoute
  '/remembered': typeof RememberedRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/the-index': typeof TheIndexRoute
  '/therapy': typeof TherapyRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/wellbeing': typeof WellbeingRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetype': typeof ArchetypeRoute
  '/ask': typeof AskRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/canvas': typeof CanvasRoute
  '/card': typeof CardRoute
  '/chat': typeof ChatRoute
  '/commit': typeof CommitRoute
  '/create': typeof CreateRoute
  '/duet': typeof DuetRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/history': typeof HistoryRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/intentions': typeof IntentionsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/programs': typeof ProgramsRoute
  '/remembered': typeof RememberedRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/the-index': typeof TheIndexRoute
  '/therapy': typeof TherapyRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/wellbeing': typeof WellbeingRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetype': typeof ArchetypeRoute
  '/ask': typeof AskRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/canvas': typeof CanvasRoute
  '/card': typeof CardRoute
  '/chat': typeof ChatRoute
  '/commit': typeof CommitRoute
  '/create': typeof CreateRoute
  '/duet': typeof DuetRoute
  '/extension': typeof ExtensionRoute
  '/future': typeof FutureRoute
  '/history': typeof HistoryRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/intentions': typeof IntentionsRoute
  '/on-this-day': typeof OnThisDayRoute
  '/onboarding': typeof OnboardingRoute
  '/programs': typeof ProgramsRoute
  '/remembered': typeof RememberedRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/the-index': typeof TheIndexRoute
  '/therapy': typeof TherapyRoute
  '/today': typeof TodayRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/wellbeing': typeof WellbeingRoute
  '/wrapped': typeof WrappedRoute
  '/year': typeof YearRoute
  '/r/$slug': typeof RSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetype'
    | '/ask'
    | '/assistant'
    | '/calendar'
    | '/canvas'
    | '/card'
    | '/chat'
    | '/commit'
    | '/create'
    | '/duet'
    | '/extension'
    | '/future'
    | '/history'
    | '/identity'
    | '/insights'
    | '/intentions'
    | '/on-this-day'
    | '/onboarding'
    | '/programs'
    | '/remembered'
    | '/research'
    | '/settings'
    | '/stats'
    | '/the-index'
    | '/therapy'
    | '/today'
    | '/upgrade'
    | '/verify'
    | '/wellbeing'
    | '/wrapped'
    | '/year'
    | '/r/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetype'
    | '/ask'
    | '/assistant'
    | '/calendar'
    | '/canvas'
    | '/card'
    | '/chat'
    | '/commit'
    | '/create'
    | '/duet'
    | '/extension'
    | '/future'
    | '/history'
    | '/identity'
    | '/insights'
    | '/intentions'
    | '/on-this-day'
    | '/onboarding'
    | '/programs'
    | '/remembered'
    | '/research'
    | '/settings'
    | '/stats'
    | '/the-index'
    | '/therapy'
    | '/today'
    | '/upgrade'
    | '/verify'
    | '/wellbeing'
    | '/wrapped'
    | '/year'
    | '/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/archetype'
    | '/ask'
    | '/assistant'
    | '/calendar'
    | '/canvas'
    | '/card'
    | '/chat'
    | '/commit'
    | '/create'
    | '/duet'
    | '/extension'
    | '/future'
    | '/history'
    | '/identity'
    | '/insights'
    | '/intentions'
    | '/on-this-day'
    | '/onboarding'
    | '/programs'
    | '/remembered'
    | '/research'
    | '/settings'
    | '/stats'
    | '/the-index'
    | '/therapy'
    | '/today'
    | '/upgrade'
    | '/verify'
    | '/wellbeing'
    | '/wrapped'
    | '/year'
    | '/r/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypeRoute: typeof ArchetypeRoute
  AskRoute: typeof AskRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  CanvasRoute: typeof CanvasRoute
  CardRoute: typeof CardRoute
  ChatRoute: typeof ChatRoute
  CommitRoute: typeof CommitRoute
  CreateRoute: typeof CreateRoute
  DuetRoute: typeof DuetRoute
  ExtensionRoute: typeof ExtensionRoute
  FutureRoute: typeof FutureRoute
  HistoryRoute: typeof HistoryRoute
  IdentityRoute: typeof IdentityRoute
  InsightsRoute: typeof InsightsRoute
  IntentionsRoute: typeof IntentionsRoute
  OnThisDayRoute: typeof OnThisDayRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgramsRoute: typeof ProgramsRoute
  RememberedRoute: typeof RememberedRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TheIndexRoute: typeof TheIndexRoute
  TherapyRoute: typeof TherapyRoute
  TodayRoute: typeof TodayRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyRoute: typeof VerifyRoute
  WellbeingRoute: typeof WellbeingRoute
  WrappedRoute: typeof WrappedRoute
  YearRoute: typeof YearRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year': {
      id: '/year'
      path: '/year'
      fullPath: '/year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellbeing': {
      id: '/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof WellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-index': {
      id: '/the-index'
      path: '/the-index'
      fullPath: '/the-index'
      preLoaderRoute: typeof TheIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remembered': {
      id: '/remembered'
      path: '/remembered'
      fullPath: '/remembered'
      preLoaderRoute: typeof RememberedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-this-day': {
      id: '/on-this-day'
      path: '/on-this-day'
      fullPath: '/on-this-day'
      preLoaderRoute: typeof OnThisDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intentions': {
      id: '/intentions'
      path: '/intentions'
      fullPath: '/intentions'
      preLoaderRoute: typeof IntentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duet': {
      id: '/duet'
      path: '/duet'
      fullPath: '/duet'
      preLoaderRoute: typeof DuetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commit': {
      id: '/commit'
      path: '/commit'
      fullPath: '/commit'
      preLoaderRoute: typeof CommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetype': {
      id: '/archetype'
      path: '/archetype'
      fullPath: '/archetype'
      preLoaderRoute: typeof ArchetypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypeRoute: ArchetypeRoute,
  AskRoute: AskRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  CanvasRoute: CanvasRoute,
  CardRoute: CardRoute,
  ChatRoute: ChatRoute,
  CommitRoute: CommitRoute,
  CreateRoute: CreateRoute,
  DuetRoute: DuetRoute,
  ExtensionRoute: ExtensionRoute,
  FutureRoute: FutureRoute,
  HistoryRoute: HistoryRoute,
  IdentityRoute: IdentityRoute,
  InsightsRoute: InsightsRoute,
  IntentionsRoute: IntentionsRoute,
  OnThisDayRoute: OnThisDayRoute,
  OnboardingRoute: OnboardingRoute,
  ProgramsRoute: ProgramsRoute,
  RememberedRoute: RememberedRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TheIndexRoute: TheIndexRoute,
  TherapyRoute: TherapyRoute,
  TodayRoute: TodayRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyRoute: VerifyRoute,
  WellbeingRoute: WellbeingRoute,
  WrappedRoute: WrappedRoute,
  YearRoute: YearRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
